name: CI

on:
  push:
    branches: [ master ]

env:
  REACT_APP_APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.REACT_APP_APPINSIGHTS_INSTRUMENTATIONKEY }}
  REACT_APP_AUTH_AAD_AUTHORITY: ${{ secrets.REACT_APP_AUTH_AAD_AUTHORITY }}
  REACT_APP_AUTH_CLIENTID: ${{ secrets.REACT_APP_AUTH_CLIENTID }}
  REACT_APP_AUTH_REDIRECTURL: ${{ secrets.APPSERVICE_REACT_APP_AUTH_REDIRECTURL }}
  REACT_APP_AUTH_SCOPE: ${{ secrets.REACT_APP_AUTH_SCOPE }}
  REACT_APP_SKILL_API_URL: ${{ secrets.REACT_APP_SKILL_API_URL }}
  REACT_APP_FREETRACK_API_URL: ${{ secrets.REACT_APP_FREETRACK_API_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -t ${{ secrets.ACR_NAME }}/plainbcntrainingsweb:${{ github.sha }} -t ${{ secrets.ACR_NAME }}/plainbcntrainingsweb:latest
          docker image push --all-tags ${{ secrets.ACR_NAME }}/plainbcntrainingsweb
