name: storage

on:
  push:
    branches:
      - master
env:
  REACT_APP_APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.REACT_APP_APPINSIGHTS_INSTRUMENTATIONKEY }}
  REACT_APP_AUTH_AAD_AUTHORITY: ${{ secrets.REACT_APP_AUTH_AAD_AUTHORITY }}
  REACT_APP_AUTH_CLIENTID: ${{ secrets.REACT_APP_AUTH_CLIENTID }}
  REACT_APP_AUTH_REDIRECTURL: ${{ secrets.STORAGE_REACT_APP_AUTH_REDIRECTURL }}
  REACT_APP_AUTH_SCOPE: ${{ secrets.REACT_APP_AUTH_SCOPE }}
  REACT_APP_SKILL_API_URL: ${{ secrets.REACT_APP_SKILL_API_URL }}
  REACT_APP_FREETRACK_API_URL: ${{ secrets.REACT_APP_FREETRACK_API_URL }}

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@master
          
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present

      - name: Deploy to Azure Storage
        uses: TravisSpomer/deploy-to-azure-storage@v1.3.0
        with:
          source-path: build
          sas-url: ${{ secrets.STORAGE_SAS_URL }}
